@startuml DA-Klassendiagramm
entity User {
    id: number <<generated>>
    --
    email: string
    username: string
    password: hashed
    icon_url: string
}

entity Exhibition {
    id: number <<generated>>
    --
    thumbnail_url: string
    title: string
    room_id: number
    description: string
}
entity Themes {
    id: number <<generated>>
    --
    thumbnail_url: string
    mat_wall_or_object: string
    mat_floor: string <<nullable>>
    light_intensity: number
    model_path: string <<nullable>>
    is_exhibit: boolean
}

entity Room {
    id : number <<generated>>
    --
    name: string◊
    positions_amount : number
    room_url: string
}

entity Position{
    id : number <<generated>>
    room_id : number
    ---
    x : number
    y : number
    is_Wall : boolean
}

entity Exhibition_Category {
    exhibition_id : number
    category_id : number
}

entity Category{
   id : number <<generated>>
   --
   title: string
   color: varchar2(6)
}

entity Exhibit {
    id: number <<generated>> 
    --
    url: string
    datatype: string
    title: string
    desc: string
}

User ||--o{ Exhibition
Exhibit ||--|{Exhibition
Exhibit ||--|| Position
Exhibition }o--|| Exhibition_Category
Exhibition_Category ||--o{ Category
Room ||--o{ Position
Exhibition }o--|| Room
Themes ||--o{ Exhibition
Themes ||--o{ Exhibit
@enduml