# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  MVN: mvn --show-version --batch-mode

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build Quarkus Backend

    steps:
      - name: checking code
        uses: actions/checkout@master
        
      - name: jdk17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      #- name: run server
      #  run: ./mvnw compile quarkus:dev
      #  working-directory: ./Server/three-d-portfolio-server/

      - name: build image for easier upload
        working-directory: ./Server/three-d-portfolio-server/
        run: | 
          mvn package -D quarkus.package.type=uber-jar
          pwd 
          ls -l
      
      - name: upload "three-d-portfolio-server-runner.jar" to "target"
        uses: actions/upload-artifact@v3
        with:
          name: three-d-portfolio-server-runner
          path: ./Server/three-d-portfolio-server/target/